# sayoDB Server Configuration File

# Network & Transport
port 6380
host 127.0.0.1
maxconnections 10000
timeout 0

# Security & Authentication
# requirepass secretpass

# Memory Management
# maxmemory limit in bytes or unit (e.g. 256mb, 1gb, 0 = unlimited). Default: 256mb (secure default limit)
maxmemory 256mb
# Eviction policy options: noeviction, allkeys-lru, volatile-lru, allkeys-lfu
maxmemory-policy noeviction
# Default TTL for keys in seconds if not specified on key creation (0 = persistent / unlimited)
default-ttl 60

# Persistence - Append Only File (AOF)
appendonly yes
appendfilename "sayodb.aof"
# fsync options: always, everysec, no
appendfsync everysec

# Persistence - RDB Snapshotting
save-rdb-filename "dump.rdb"
save 900 1
save 300 10
save 60 10000

# Logging & Debugging
# loglevel options: debug, info, warn, error
loglevel info
